"""Populate the database with a broad catalog of meals so every dietary
type has real breakfast/lunch/dinner variety for recommendations, weekly
planning, and grocery lists to work with.

Run with: python seed_data.py
"""

import models
from database import Base, SessionLocal, engine

# ---------------------------------------------------------------------------
# Breakfast
# ---------------------------------------------------------------------------

BREAKFAST_MEALS = [
    {
        "name": "Oatmeal with Berries",
        "description": "Rolled oats topped with mixed berries and honey.",
        "meal_type": models.MealType.BREAKFAST,
        "calories": 350,
        "protein_g": 10,
        "carbs_g": 60,
        "fat_g": 6,
        "dietary_tags": ["vegetarian", "vegan", "gluten_free"],
        "allergens": [],
        "ingredients": [
            {"name": "rolled oats", "quantity": 1, "unit": "cup"},
            {"name": "mixed berries", "quantity": 0.5, "unit": "cup"},
            {"name": "honey", "quantity": 1, "unit": "tbsp"},
        ],
    },
    {
        "name": "Greek Yogurt Parfait",
        "description": "Greek yogurt layered with granola and honey.",
        "meal_type": models.MealType.BREAKFAST,
        "calories": 320,
        "protein_g": 20,
        "carbs_g": 40,
        "fat_g": 8,
        "dietary_tags": ["vegetarian", "high_protein"],
        "allergens": ["dairy"],
        "ingredients": [
            {"name": "greek yogurt", "quantity": 1, "unit": "cup"},
            {"name": "granola", "quantity": 0.5, "unit": "cup"},
            {"name": "honey", "quantity": 1, "unit": "tbsp"},
        ],
    },
    {
        "name": "Veggie Scramble",
        "description": "Scrambled eggs with bell peppers, onion, and spinach.",
        "meal_type": models.MealType.BREAKFAST,
        "calories": 400,
        "protein_g": 24,
        "carbs_g": 12,
        "fat_g": 26,
        "dietary_tags": ["vegetarian", "gluten_free", "keto", "paleo", "high_protein", "low_carb"],
        "allergens": ["eggs"],
        "ingredients": [
            {"name": "eggs", "quantity": 3, "unit": "unit"},
            {"name": "bell pepper", "quantity": 0.5, "unit": "unit"},
            {"name": "onion", "quantity": 0.25, "unit": "unit"},
            {"name": "spinach", "quantity": 1, "unit": "cup"},
        ],
    },
    {
        "name": "Peanut Butter Banana Toast",
        "description": "Whole grain toast with peanut butter and banana.",
        "meal_type": models.MealType.BREAKFAST,
        "calories": 380,
        "protein_g": 12,
        "carbs_g": 52,
        "fat_g": 14,
        "dietary_tags": ["vegetarian", "vegan"],
        "allergens": ["peanuts", "gluten"],
        "ingredients": [
            {"name": "whole grain bread", "quantity": 2, "unit": "slice"},
            {"name": "peanut butter", "quantity": 2, "unit": "tbsp"},
            {"name": "banana", "quantity": 1, "unit": "unit"},
        ],
    },
    {
        "name": "Tofu Scramble",
        "description": "Turmeric-spiced crumbled tofu with peppers and onion.",
        "meal_type": models.MealType.BREAKFAST,
        "calories": 340,
        "protein_g": 22,
        "carbs_g": 18,
        "fat_g": 20,
        "dietary_tags": ["vegan", "vegetarian", "gluten_free", "high_protein"],
        "allergens": ["soy"],
        "ingredients": [
            {"name": "tofu", "quantity": 8, "unit": "oz"},
            {"name": "bell pepper", "quantity": 0.5, "unit": "unit"},
            {"name": "onion", "quantity": 0.25, "unit": "unit"},
            {"name": "nutritional yeast", "quantity": 2, "unit": "tbsp"},
        ],
    },
    {
        "name": "Smoked Salmon Bagel",
        "description": "Bagel with smoked salmon, cream cheese, and red onion.",
        "meal_type": models.MealType.BREAKFAST,
        "calories": 420,
        "protein_g": 26,
        "carbs_g": 48,
        "fat_g": 14,
        "dietary_tags": ["pescatarian", "high_protein"],
        "allergens": ["fish", "dairy", "gluten"],
        "ingredients": [
            {"name": "bagel", "quantity": 1, "unit": "unit"},
            {"name": "smoked salmon", "quantity": 3, "unit": "oz"},
            {"name": "cream cheese", "quantity": 2, "unit": "tbsp"},
            {"name": "red onion", "quantity": 0.25, "unit": "unit"},
        ],
    },
    {
        "name": "Chia Seed Pudding",
        "description": "Chia seeds soaked overnight in almond milk with berries.",
        "meal_type": models.MealType.BREAKFAST,
        "calories": 300,
        "protein_g": 9,
        "carbs_g": 22,
        "fat_g": 18,
        "dietary_tags": ["vegan", "vegetarian", "gluten_free", "low_carb"],
        "allergens": ["nuts"],
        "ingredients": [
            {"name": "chia seeds", "quantity": 3, "unit": "tbsp"},
            {"name": "almond milk", "quantity": 1, "unit": "cup"},
            {"name": "honey", "quantity": 1, "unit": "tbsp"},
            {"name": "mixed berries", "quantity": 0.5, "unit": "cup"},
        ],
    },
    {
        "name": "Avocado Toast with Poached Egg",
        "description": "Mashed avocado and a poached egg on toasted bread.",
        "meal_type": models.MealType.BREAKFAST,
        "calories": 380,
        "protein_g": 16,
        "carbs_g": 34,
        "fat_g": 20,
        "dietary_tags": ["vegetarian"],
        "allergens": ["eggs", "gluten"],
        "ingredients": [
            {"name": "whole grain bread", "quantity": 2, "unit": "slice"},
            {"name": "avocado", "quantity": 1, "unit": "unit"},
            {"name": "eggs", "quantity": 2, "unit": "unit"},
            {"name": "lemon", "quantity": 0.5, "unit": "unit"},
        ],
    },
    {
        "name": "Keto Egg Muffins",
        "description": "Baked egg muffins with bacon, spinach, and cheddar.",
        "meal_type": models.MealType.BREAKFAST,
        "calories": 320,
        "protein_g": 24,
        "carbs_g": 6,
        "fat_g": 22,
        "dietary_tags": ["keto", "gluten_free", "paleo", "high_protein", "low_carb"],
        "allergens": ["eggs", "dairy"],
        "ingredients": [
            {"name": "eggs", "quantity": 4, "unit": "unit"},
            {"name": "spinach", "quantity": 1, "unit": "cup"},
            {"name": "bacon", "quantity": 2, "unit": "slice"},
            {"name": "cheddar cheese", "quantity": 0.25, "unit": "cup"},
        ],
    },
    {
        "name": "Smoothie Bowl",
        "description": "Blended frozen berries and banana topped with granola.",
        "meal_type": models.MealType.BREAKFAST,
        "calories": 360,
        "protein_g": 8,
        "carbs_g": 64,
        "fat_g": 10,
        "dietary_tags": ["vegan", "vegetarian", "gluten_free"],
        "allergens": [],
        "ingredients": [
            {"name": "frozen berries", "quantity": 1.5, "unit": "cup"},
            {"name": "banana", "quantity": 1, "unit": "unit"},
            {"name": "almond milk", "quantity": 0.5, "unit": "cup"},
            {"name": "granola", "quantity": 0.25, "unit": "cup"},
        ],
    },
    {
        "name": "Breakfast Burrito",
        "description": "Scrambled eggs, turkey sausage, and cheese in a tortilla.",
        "meal_type": models.MealType.BREAKFAST,
        "calories": 520,
        "protein_g": 28,
        "carbs_g": 46,
        "fat_g": 24,
        "dietary_tags": ["high_protein"],
        "allergens": ["eggs", "dairy", "gluten"],
        "ingredients": [
            {"name": "tortilla", "quantity": 1, "unit": "unit"},
            {"name": "eggs", "quantity": 3, "unit": "unit"},
            {"name": "turkey sausage", "quantity": 3, "unit": "oz"},
            {"name": "cheddar cheese", "quantity": 0.25, "unit": "cup"},
            {"name": "bell pepper", "quantity": 0.5, "unit": "unit"},
        ],
    },
    {
        "name": "Shakshuka",
        "description": "Eggs poached in a spiced tomato and pepper sauce.",
        "meal_type": models.MealType.BREAKFAST,
        "calories": 360,
        "protein_g": 18,
        "carbs_g": 22,
        "fat_g": 22,
        "dietary_tags": ["vegetarian", "gluten_free"],
        "allergens": ["eggs", "dairy"],
        "ingredients": [
            {"name": "eggs", "quantity": 3, "unit": "unit"},
            {"name": "tomato sauce", "quantity": 1, "unit": "cup"},
            {"name": "bell pepper", "quantity": 0.5, "unit": "unit"},
            {"name": "onion", "quantity": 0.25, "unit": "unit"},
            {"name": "feta cheese", "quantity": 0.25, "unit": "cup"},
        ],
    },
    {
        "name": "Steel Cut Oats with Almond Butter",
        "description": "Creamy steel cut oats swirled with almond butter and banana.",
        "meal_type": models.MealType.BREAKFAST,
        "calories": 370,
        "protein_g": 11,
        "carbs_g": 54,
        "fat_g": 13,
        "dietary_tags": ["vegan", "vegetarian", "gluten_free"],
        "allergens": ["nuts"],
        "ingredients": [
            {"name": "steel cut oats", "quantity": 1, "unit": "cup"},
            {"name": "almond butter", "quantity": 2, "unit": "tbsp"},
            {"name": "banana", "quantity": 1, "unit": "unit"},
        ],
    },
    {
        "name": "Cottage Cheese with Pineapple",
        "description": "Cottage cheese topped with fresh pineapple chunks.",
        "meal_type": models.MealType.BREAKFAST,
        "calories": 260,
        "protein_g": 24,
        "carbs_g": 20,
        "fat_g": 6,
        "dietary_tags": ["vegetarian", "high_protein", "gluten_free", "low_carb"],
        "allergens": ["dairy"],
        "ingredients": [
            {"name": "cottage cheese", "quantity": 1, "unit": "cup"},
            {"name": "pineapple", "quantity": 0.75, "unit": "cup"},
        ],
    },
    {
        "name": "Paleo Breakfast Hash",
        "description": "Sweet potato hash with bacon, onion, and fried eggs.",
        "meal_type": models.MealType.BREAKFAST,
        "calories": 420,
        "protein_g": 22,
        "carbs_g": 28,
        "fat_g": 24,
        "dietary_tags": ["paleo", "gluten_free", "high_protein"],
        "allergens": ["eggs"],
        "ingredients": [
            {"name": "sweet potato", "quantity": 1, "unit": "unit"},
            {"name": "bacon", "quantity": 3, "unit": "slice"},
            {"name": "eggs", "quantity": 2, "unit": "unit"},
            {"name": "onion", "quantity": 0.25, "unit": "unit"},
        ],
    },
    {
        "name": "Smoked Trout & Cream Cheese Bagel",
        "description": "Bagel topped with smoked trout, cream cheese, and cucumber.",
        "meal_type": models.MealType.BREAKFAST,
        "calories": 430,
        "protein_g": 25,
        "carbs_g": 46,
        "fat_g": 16,
        "dietary_tags": ["pescatarian", "high_protein"],
        "allergens": ["fish", "dairy", "gluten"],
        "ingredients": [
            {"name": "bagel", "quantity": 1, "unit": "unit"},
            {"name": "smoked trout", "quantity": 3, "unit": "oz"},
            {"name": "cream cheese", "quantity": 2, "unit": "tbsp"},
            {"name": "cucumber", "quantity": 0.25, "unit": "unit"},
        ],
    },
    {
        "name": "Buckwheat Pancakes",
        "description": "Fluffy pancakes made with naturally gluten-free buckwheat flour.",
        "meal_type": models.MealType.BREAKFAST,
        "calories": 360,
        "protein_g": 10,
        "carbs_g": 58,
        "fat_g": 10,
        "dietary_tags": ["vegetarian", "vegan", "gluten_free"],
        "allergens": [],
        "ingredients": [
            {"name": "buckwheat flour", "quantity": 1, "unit": "cup"},
            {"name": "almond milk", "quantity": 1, "unit": "cup"},
            {"name": "banana", "quantity": 1, "unit": "unit"},
            {"name": "honey", "quantity": 1, "unit": "tbsp"},
        ],
    },
    {
        "name": "Protein Pancakes",
        "description": "Protein-packed pancakes made with oats and protein powder.",
        "meal_type": models.MealType.BREAKFAST,
        "calories": 400,
        "protein_g": 30,
        "carbs_g": 42,
        "fat_g": 12,
        "dietary_tags": ["vegetarian", "high_protein"],
        "allergens": ["eggs"],
        "ingredients": [
            {"name": "protein powder", "quantity": 1, "unit": "scoop"},
            {"name": "eggs", "quantity": 2, "unit": "unit"},
            {"name": "rolled oats", "quantity": 0.5, "unit": "cup"},
            {"name": "banana", "quantity": 1, "unit": "unit"},
        ],
    },
    {
        "name": "Bacon and Eggs",
        "description": "A classic plate of crispy bacon and fried eggs.",
        "meal_type": models.MealType.BREAKFAST,
        "calories": 420,
        "protein_g": 26,
        "carbs_g": 4,
        "fat_g": 34,
        "dietary_tags": ["keto", "paleo", "gluten_free", "high_protein", "low_carb"],
        "allergens": ["eggs"],
        "ingredients": [
            {"name": "eggs", "quantity": 3, "unit": "unit"},
            {"name": "bacon", "quantity": 4, "unit": "slice"},
        ],
    },
    {
        "name": "Low-Carb Breakfast Wrap",
        "description": "Scrambled eggs and cheese in a low-carb tortilla.",
        "meal_type": models.MealType.BREAKFAST,
        "calories": 340,
        "protein_g": 22,
        "carbs_g": 14,
        "fat_g": 22,
        "dietary_tags": ["low_carb", "vegetarian", "gluten_free"],
        "allergens": ["eggs", "dairy"],
        "ingredients": [
            {"name": "low-carb tortilla", "quantity": 1, "unit": "unit"},
            {"name": "eggs", "quantity": 2, "unit": "unit"},
            {"name": "cheddar cheese", "quantity": 0.25, "unit": "cup"},
            {"name": "spinach", "quantity": 1, "unit": "cup"},
        ],
    },
    {
        "name": "Smoked Salmon & Avocado Plate",
        "description": "Smoked salmon with avocado, cucumber, and lemon.",
        "meal_type": models.MealType.BREAKFAST,
        "calories": 380,
        "protein_g": 24,
        "carbs_g": 10,
        "fat_g": 28,
        "dietary_tags": ["pescatarian", "keto", "gluten_free", "paleo", "high_protein", "low_carb"],
        "allergens": ["fish"],
        "ingredients": [
            {"name": "smoked salmon", "quantity": 3, "unit": "oz"},
            {"name": "avocado", "quantity": 1, "unit": "unit"},
            {"name": "cucumber", "quantity": 0.5, "unit": "unit"},
            {"name": "lemon", "quantity": 0.5, "unit": "unit"},
        ],
    },
    {
        "name": "Muesli with Yogurt",
        "description": "Swiss-style muesli soaked in yogurt with fresh berries.",
        "meal_type": models.MealType.BREAKFAST,
        "calories": 340,
        "protein_g": 14,
        "carbs_g": 56,
        "fat_g": 8,
        "dietary_tags": ["vegetarian"],
        "allergens": ["dairy", "gluten"],
        "ingredients": [
            {"name": "muesli", "quantity": 1, "unit": "cup"},
            {"name": "greek yogurt", "quantity": 0.5, "unit": "cup"},
            {"name": "mixed berries", "quantity": 0.5, "unit": "cup"},
        ],
    },
    {
        "name": "Egg White Veggie Omelette",
        "description": "A fluffy egg white omelette with spinach, mushroom, and feta.",
        "meal_type": models.MealType.BREAKFAST,
        "calories": 300,
        "protein_g": 28,
        "carbs_g": 10,
        "fat_g": 16,
        "dietary_tags": ["vegetarian", "gluten_free", "high_protein", "low_carb", "keto"],
        "allergens": ["eggs", "dairy"],
        "ingredients": [
            {"name": "egg whites", "quantity": 5, "unit": "unit"},
            {"name": "spinach", "quantity": 1, "unit": "cup"},
            {"name": "mushroom", "quantity": 0.5, "unit": "cup"},
            {"name": "feta cheese", "quantity": 0.25, "unit": "cup"},
        ],
    },
    {
        "name": "Smoked Salmon Scrambled Eggs",
        "description": "Soft scrambled eggs folded with smoked salmon and cream cheese.",
        "meal_type": models.MealType.BREAKFAST,
        "calories": 380,
        "protein_g": 28,
        "carbs_g": 6,
        "fat_g": 26,
        "dietary_tags": ["pescatarian", "gluten_free", "high_protein", "low_carb", "keto"],
        "allergens": ["eggs", "fish", "dairy"],
        "ingredients": [
            {"name": "eggs", "quantity": 3, "unit": "unit"},
            {"name": "smoked salmon", "quantity": 2, "unit": "oz"},
            {"name": "cream cheese", "quantity": 1, "unit": "tbsp"},
        ],
    },
    {
        "name": "Egg & Smoked Salmon Muffins",
        "description": "Baked egg muffins with smoked salmon and spinach.",
        "meal_type": models.MealType.BREAKFAST,
        "calories": 320,
        "protein_g": 24,
        "carbs_g": 6,
        "fat_g": 20,
        "dietary_tags": ["pescatarian", "gluten_free", "high_protein", "low_carb"],
        "allergens": ["eggs", "fish", "dairy"],
        "ingredients": [
            {"name": "eggs", "quantity": 4, "unit": "unit"},
            {"name": "smoked salmon", "quantity": 2, "unit": "oz"},
            {"name": "spinach", "quantity": 1, "unit": "cup"},
            {"name": "cream cheese", "quantity": 1, "unit": "tbsp"},
        ],
    },
]

# ---------------------------------------------------------------------------
# Lunch
# ---------------------------------------------------------------------------

LUNCH_MEALS = [
    {
        "name": "Grilled Chicken Salad",
        "description": "Mixed greens with grilled chicken, tomato, and vinaigrette.",
        "meal_type": models.MealType.LUNCH,
        "calories": 480,
        "protein_g": 40,
        "carbs_g": 18,
        "fat_g": 26,
        "dietary_tags": ["gluten_free", "paleo", "keto", "high_protein", "low_carb"],
        "allergens": [],
        "ingredients": [
            {"name": "chicken breast", "quantity": 6, "unit": "oz"},
            {"name": "mixed greens", "quantity": 2, "unit": "cup"},
            {"name": "cherry tomatoes", "quantity": 0.5, "unit": "cup"},
            {"name": "olive oil vinaigrette", "quantity": 2, "unit": "tbsp"},
        ],
    },
    {
        "name": "Falafel Wrap",
        "description": "Falafel, hummus, and vegetables in a whole wheat wrap.",
        "meal_type": models.MealType.LUNCH,
        "calories": 550,
        "protein_g": 18,
        "carbs_g": 68,
        "fat_g": 22,
        "dietary_tags": ["vegetarian", "vegan"],
        "allergens": ["gluten", "sesame"],
        "ingredients": [
            {"name": "falafel", "quantity": 5, "unit": "unit"},
            {"name": "whole wheat wrap", "quantity": 1, "unit": "unit"},
            {"name": "hummus", "quantity": 3, "unit": "tbsp"},
            {"name": "cucumber", "quantity": 0.5, "unit": "unit"},
        ],
    },
    {
        "name": "Shrimp Tacos",
        "description": "Seared shrimp in corn tortillas with cabbage slaw.",
        "meal_type": models.MealType.LUNCH,
        "calories": 520,
        "protein_g": 32,
        "carbs_g": 46,
        "fat_g": 20,
        "dietary_tags": ["pescatarian", "gluten_free", "high_protein"],
        "allergens": ["shellfish"],
        "ingredients": [
            {"name": "shrimp", "quantity": 6, "unit": "oz"},
            {"name": "corn tortillas", "quantity": 3, "unit": "unit"},
            {"name": "cabbage slaw", "quantity": 1, "unit": "cup"},
            {"name": "lime", "quantity": 1, "unit": "unit"},
        ],
    },
    {
        "name": "Quinoa Buddha Bowl",
        "description": "Quinoa, roasted vegetables, and tahini dressing.",
        "meal_type": models.MealType.LUNCH,
        "calories": 500,
        "protein_g": 16,
        "carbs_g": 64,
        "fat_g": 18,
        "dietary_tags": ["vegetarian", "vegan", "gluten_free"],
        "allergens": ["sesame"],
        "ingredients": [
            {"name": "quinoa", "quantity": 1, "unit": "cup"},
            {"name": "roasted sweet potato", "quantity": 1, "unit": "cup"},
            {"name": "chickpeas", "quantity": 0.5, "unit": "cup"},
            {"name": "tahini dressing", "quantity": 2, "unit": "tbsp"},
        ],
    },
    {
        "name": "Turkey Club Sandwich",
        "description": "Turkey, bacon, lettuce, and tomato on toasted bread.",
        "meal_type": models.MealType.LUNCH,
        "calories": 560,
        "protein_g": 34,
        "carbs_g": 42,
        "fat_g": 28,
        "dietary_tags": ["high_protein"],
        "allergens": ["gluten"],
        "ingredients": [
            {"name": "turkey breast", "quantity": 4, "unit": "oz"},
            {"name": "bacon", "quantity": 2, "unit": "slice"},
            {"name": "bread", "quantity": 3, "unit": "slice"},
            {"name": "lettuce", "quantity": 2, "unit": "leaf"},
            {"name": "tomato", "quantity": 0.5, "unit": "unit"},
        ],
    },
    {
        "name": "Tuna Nicoise Salad",
        "description": "Canned tuna with eggs, green beans, olives, and tomato.",
        "meal_type": models.MealType.LUNCH,
        "calories": 440,
        "protein_g": 34,
        "carbs_g": 16,
        "fat_g": 26,
        "dietary_tags": ["pescatarian", "gluten_free", "high_protein", "low_carb"],
        "allergens": ["fish", "eggs"],
        "ingredients": [
            {"name": "canned tuna", "quantity": 1, "unit": "cup"},
            {"name": "eggs", "quantity": 2, "unit": "unit"},
            {"name": "green beans", "quantity": 1, "unit": "cup"},
            {"name": "olives", "quantity": 2, "unit": "tbsp"},
            {"name": "cherry tomatoes", "quantity": 0.5, "unit": "cup"},
        ],
    },
    {
        "name": "Poke Bowl",
        "description": "Marinated ahi tuna over rice with cucumber and avocado.",
        "meal_type": models.MealType.LUNCH,
        "calories": 520,
        "protein_g": 30,
        "carbs_g": 58,
        "fat_g": 16,
        "dietary_tags": ["pescatarian", "gluten_free", "high_protein"],
        "allergens": ["fish", "soy"],
        "ingredients": [
            {"name": "tuna steak", "quantity": 6, "unit": "oz"},
            {"name": "jasmine rice", "quantity": 1, "unit": "cup"},
            {"name": "cucumber", "quantity": 0.5, "unit": "unit"},
            {"name": "avocado", "quantity": 0.5, "unit": "unit"},
            {"name": "tamari", "quantity": 1, "unit": "tbsp"},
        ],
    },
    {
        "name": "Salmon & Avocado Salad",
        "description": "Seared salmon over greens with avocado and olive oil.",
        "meal_type": models.MealType.LUNCH,
        "calories": 460,
        "protein_g": 30,
        "carbs_g": 12,
        "fat_g": 32,
        "dietary_tags": ["pescatarian", "keto", "gluten_free", "paleo", "high_protein", "low_carb"],
        "allergens": ["fish"],
        "ingredients": [
            {"name": "salmon fillet", "quantity": 5, "unit": "oz"},
            {"name": "mixed greens", "quantity": 2, "unit": "cup"},
            {"name": "avocado", "quantity": 0.5, "unit": "unit"},
            {"name": "cherry tomatoes", "quantity": 0.5, "unit": "cup"},
            {"name": "olive oil", "quantity": 1, "unit": "tbsp"},
        ],
    },
    {
        "name": "Shrimp & Avocado Salad",
        "description": "Chilled shrimp over greens with avocado and lime.",
        "meal_type": models.MealType.LUNCH,
        "calories": 420,
        "protein_g": 28,
        "carbs_g": 12,
        "fat_g": 28,
        "dietary_tags": ["pescatarian", "keto", "gluten_free", "paleo", "high_protein", "low_carb"],
        "allergens": ["shellfish"],
        "ingredients": [
            {"name": "shrimp", "quantity": 6, "unit": "oz"},
            {"name": "mixed greens", "quantity": 2, "unit": "cup"},
            {"name": "avocado", "quantity": 0.5, "unit": "unit"},
            {"name": "lime", "quantity": 1, "unit": "unit"},
            {"name": "olive oil", "quantity": 1, "unit": "tbsp"},
        ],
    },
    {
        "name": "California Roll Bowl",
        "description": "Deconstructed sushi bowl with crab, rice, and avocado.",
        "meal_type": models.MealType.LUNCH,
        "calories": 460,
        "protein_g": 20,
        "carbs_g": 60,
        "fat_g": 14,
        "dietary_tags": ["pescatarian", "gluten_free"],
        "allergens": ["shellfish", "soy"],
        "ingredients": [
            {"name": "crab meat", "quantity": 4, "unit": "oz"},
            {"name": "jasmine rice", "quantity": 1, "unit": "cup"},
            {"name": "cucumber", "quantity": 0.5, "unit": "unit"},
            {"name": "avocado", "quantity": 0.5, "unit": "unit"},
            {"name": "tamari", "quantity": 1, "unit": "tbsp"},
        ],
    },
    {
        "name": "Chickpea Salad Sandwich",
        "description": "Mashed chickpea salad on bread with celery and vegan mayo.",
        "meal_type": models.MealType.LUNCH,
        "calories": 460,
        "protein_g": 16,
        "carbs_g": 58,
        "fat_g": 18,
        "dietary_tags": ["vegetarian", "vegan"],
        "allergens": ["gluten"],
        "ingredients": [
            {"name": "chickpeas", "quantity": 1.5, "unit": "cup"},
            {"name": "bread", "quantity": 2, "unit": "slice"},
            {"name": "celery", "quantity": 1, "unit": "stalk"},
            {"name": "vegan mayo", "quantity": 2, "unit": "tbsp"},
        ],
    },
    {
        "name": "Black Bean Burrito Bowl",
        "description": "Black beans, rice, corn, and salsa in a bowl.",
        "meal_type": models.MealType.LUNCH,
        "calories": 540,
        "protein_g": 22,
        "carbs_g": 74,
        "fat_g": 16,
        "dietary_tags": ["vegetarian", "vegan", "gluten_free", "high_protein"],
        "allergens": [],
        "ingredients": [
            {"name": "black beans", "quantity": 1.5, "unit": "cup"},
            {"name": "jasmine rice", "quantity": 1, "unit": "cup"},
            {"name": "sweet corn", "quantity": 0.5, "unit": "cup"},
            {"name": "salsa", "quantity": 0.25, "unit": "cup"},
            {"name": "avocado", "quantity": 0.5, "unit": "unit"},
        ],
    },
    {
        "name": "Chicken Caprese Salad",
        "description": "Grilled chicken with mozzarella, tomato, and basil.",
        "meal_type": models.MealType.LUNCH,
        "calories": 460,
        "protein_g": 38,
        "carbs_g": 10,
        "fat_g": 28,
        "dietary_tags": ["gluten_free", "keto", "high_protein"],
        "allergens": ["dairy"],
        "ingredients": [
            {"name": "chicken breast", "quantity": 5, "unit": "oz"},
            {"name": "mozzarella cheese", "quantity": 0.5, "unit": "cup"},
            {"name": "cherry tomatoes", "quantity": 0.5, "unit": "cup"},
            {"name": "basil", "quantity": 6, "unit": "leaf"},
            {"name": "olive oil", "quantity": 1, "unit": "tbsp"},
        ],
    },
    {
        "name": "Steak Salad",
        "description": "Sliced sirloin steak over greens with red onion.",
        "meal_type": models.MealType.LUNCH,
        "calories": 500,
        "protein_g": 36,
        "carbs_g": 14,
        "fat_g": 32,
        "dietary_tags": ["keto", "paleo", "gluten_free", "high_protein", "low_carb"],
        "allergens": [],
        "ingredients": [
            {"name": "sirloin steak", "quantity": 6, "unit": "oz"},
            {"name": "mixed greens", "quantity": 2, "unit": "cup"},
            {"name": "cherry tomatoes", "quantity": 0.5, "unit": "cup"},
            {"name": "red onion", "quantity": 0.25, "unit": "unit"},
            {"name": "olive oil", "quantity": 1, "unit": "tbsp"},
        ],
    },
    {
        "name": "Turkey Lettuce Wraps",
        "description": "Ground turkey with ginger and tamari in lettuce cups.",
        "meal_type": models.MealType.LUNCH,
        "calories": 380,
        "protein_g": 32,
        "carbs_g": 12,
        "fat_g": 22,
        "dietary_tags": ["paleo", "keto", "gluten_free", "high_protein", "low_carb"],
        "allergens": ["soy"],
        "ingredients": [
            {"name": "ground turkey", "quantity": 6, "unit": "oz"},
            {"name": "lettuce", "quantity": 6, "unit": "leaf"},
            {"name": "carrot", "quantity": 1, "unit": "unit"},
            {"name": "tamari", "quantity": 1, "unit": "tbsp"},
            {"name": "ginger", "quantity": 1, "unit": "tbsp"},
        ],
    },
    {
        "name": "Chicken Caesar Salad",
        "description": "Grilled chicken over romaine with parmesan and caesar dressing.",
        "meal_type": models.MealType.LUNCH,
        "calories": 460,
        "protein_g": 36,
        "carbs_g": 10,
        "fat_g": 30,
        "dietary_tags": ["gluten_free", "keto", "high_protein"],
        "allergens": ["dairy", "fish"],
        "ingredients": [
            {"name": "chicken breast", "quantity": 5, "unit": "oz"},
            {"name": "romaine lettuce", "quantity": 2, "unit": "cup"},
            {"name": "parmesan cheese", "quantity": 2, "unit": "tbsp"},
            {"name": "caesar dressing", "quantity": 2, "unit": "tbsp"},
        ],
    },
    {
        "name": "Vegan Buddha Bowl with Tempeh",
        "description": "Marinated tempeh with quinoa and roasted broccoli.",
        "meal_type": models.MealType.LUNCH,
        "calories": 520,
        "protein_g": 24,
        "carbs_g": 58,
        "fat_g": 20,
        "dietary_tags": ["vegan", "vegetarian", "gluten_free", "high_protein"],
        "allergens": ["soy"],
        "ingredients": [
            {"name": "tempeh", "quantity": 6, "unit": "oz"},
            {"name": "quinoa", "quantity": 1, "unit": "cup"},
            {"name": "broccoli", "quantity": 1, "unit": "cup"},
            {"name": "tahini dressing", "quantity": 2, "unit": "tbsp"},
        ],
    },
    {
        "name": "Mediterranean Chickpea Salad",
        "description": "Chickpeas with cucumber, tomato, and olives in olive oil.",
        "meal_type": models.MealType.LUNCH,
        "calories": 420,
        "protein_g": 14,
        "carbs_g": 52,
        "fat_g": 18,
        "dietary_tags": ["vegetarian", "vegan", "gluten_free"],
        "allergens": [],
        "ingredients": [
            {"name": "chickpeas", "quantity": 1.5, "unit": "cup"},
            {"name": "cucumber", "quantity": 0.5, "unit": "unit"},
            {"name": "cherry tomatoes", "quantity": 0.5, "unit": "cup"},
            {"name": "olives", "quantity": 2, "unit": "tbsp"},
            {"name": "olive oil", "quantity": 1, "unit": "tbsp"},
        ],
    },
    {
        "name": "Egg Salad Lettuce Wraps",
        "description": "Classic egg salad wrapped in crisp lettuce leaves.",
        "meal_type": models.MealType.LUNCH,
        "calories": 380,
        "protein_g": 24,
        "carbs_g": 8,
        "fat_g": 28,
        "dietary_tags": ["vegetarian", "gluten_free", "keto", "high_protein", "low_carb"],
        "allergens": ["eggs"],
        "ingredients": [
            {"name": "eggs", "quantity": 4, "unit": "unit"},
            {"name": "mayo", "quantity": 2, "unit": "tbsp"},
            {"name": "lettuce", "quantity": 6, "unit": "leaf"},
            {"name": "celery", "quantity": 1, "unit": "stalk"},
        ],
    },
    {
        "name": "Cobb Salad",
        "description": "Chicken, bacon, egg, and avocado over mixed greens.",
        "meal_type": models.MealType.LUNCH,
        "calories": 520,
        "protein_g": 34,
        "carbs_g": 14,
        "fat_g": 36,
        "dietary_tags": ["gluten_free", "keto", "high_protein", "low_carb"],
        "allergens": ["eggs", "dairy"],
        "ingredients": [
            {"name": "chicken breast", "quantity": 4, "unit": "oz"},
            {"name": "bacon", "quantity": 2, "unit": "slice"},
            {"name": "eggs", "quantity": 1, "unit": "unit"},
            {"name": "avocado", "quantity": 0.5, "unit": "unit"},
            {"name": "blue cheese", "quantity": 2, "unit": "tbsp"},
            {"name": "mixed greens", "quantity": 2, "unit": "cup"},
        ],
    },
    {
        "name": "Lentil Salad",
        "description": "Cooked lentils tossed with cucumber, tomato, and olive oil.",
        "meal_type": models.MealType.LUNCH,
        "calories": 440,
        "protein_g": 20,
        "carbs_g": 60,
        "fat_g": 14,
        "dietary_tags": ["vegetarian", "vegan", "gluten_free", "high_protein"],
        "allergens": [],
        "ingredients": [
            {"name": "lentils", "quantity": 1.5, "unit": "cup"},
            {"name": "cucumber", "quantity": 0.5, "unit": "unit"},
            {"name": "cherry tomatoes", "quantity": 0.5, "unit": "cup"},
            {"name": "red onion", "quantity": 0.25, "unit": "unit"},
            {"name": "olive oil", "quantity": 1, "unit": "tbsp"},
        ],
    },
    {
        "name": "Zucchini Noodle Shrimp Scampi",
        "description": "Garlicky shrimp over spiralized zucchini noodles.",
        "meal_type": models.MealType.LUNCH,
        "calories": 400,
        "protein_g": 30,
        "carbs_g": 14,
        "fat_g": 24,
        "dietary_tags": ["pescatarian", "gluten_free", "keto", "low_carb"],
        "allergens": ["shellfish", "dairy"],
        "ingredients": [
            {"name": "shrimp", "quantity": 6, "unit": "oz"},
            {"name": "zucchini", "quantity": 2, "unit": "unit"},
            {"name": "garlic", "quantity": 2, "unit": "clove"},
            {"name": "olive oil", "quantity": 2, "unit": "tbsp"},
            {"name": "parmesan cheese", "quantity": 2, "unit": "tbsp"},
        ],
    },
    {
        "name": "Tempeh Stir Fry Bowl",
        "description": "Stir-fried tempeh with broccoli and carrot over rice.",
        "meal_type": models.MealType.LUNCH,
        "calories": 480,
        "protein_g": 26,
        "carbs_g": 50,
        "fat_g": 18,
        "dietary_tags": ["vegan", "vegetarian", "gluten_free", "high_protein"],
        "allergens": ["soy"],
        "ingredients": [
            {"name": "tempeh", "quantity": 6, "unit": "oz"},
            {"name": "broccoli", "quantity": 1, "unit": "cup"},
            {"name": "carrot", "quantity": 1, "unit": "unit"},
            {"name": "jasmine rice", "quantity": 1, "unit": "cup"},
            {"name": "tamari", "quantity": 2, "unit": "tbsp"},
        ],
    },
    {
        "name": "Ham and Swiss Sandwich",
        "description": "Sliced ham and swiss cheese with lettuce and mustard.",
        "meal_type": models.MealType.LUNCH,
        "calories": 520,
        "protein_g": 28,
        "carbs_g": 48,
        "fat_g": 22,
        "dietary_tags": [],
        "allergens": ["dairy", "gluten"],
        "ingredients": [
            {"name": "ham", "quantity": 4, "unit": "oz"},
            {"name": "swiss cheese", "quantity": 2, "unit": "slice"},
            {"name": "bread", "quantity": 2, "unit": "slice"},
            {"name": "lettuce", "quantity": 1, "unit": "leaf"},
            {"name": "mustard", "quantity": 1, "unit": "tbsp"},
        ],
    },
]

# ---------------------------------------------------------------------------
# Dinner
# ---------------------------------------------------------------------------

DINNER_MEALS = [
    {
        "name": "Baked Salmon with Asparagus",
        "description": "Oven-roasted salmon fillet with asparagus.",
        "meal_type": models.MealType.DINNER,
        "calories": 620,
        "protein_g": 44,
        "carbs_g": 14,
        "fat_g": 40,
        "dietary_tags": ["pescatarian", "gluten_free", "keto", "paleo", "high_protein", "low_carb"],
        "allergens": ["fish"],
        "ingredients": [
            {"name": "salmon fillet", "quantity": 8, "unit": "oz"},
            {"name": "asparagus", "quantity": 1, "unit": "bunch"},
            {"name": "olive oil", "quantity": 1, "unit": "tbsp"},
            {"name": "lemon", "quantity": 1, "unit": "unit"},
        ],
    },
    {
        "name": "Beef Stir Fry",
        "description": "Sliced beef and vegetables in a soy-ginger sauce over rice.",
        "meal_type": models.MealType.DINNER,
        "calories": 680,
        "protein_g": 38,
        "carbs_g": 62,
        "fat_g": 26,
        "dietary_tags": ["high_protein"],
        "allergens": ["soy", "gluten"],
        "ingredients": [
            {"name": "beef sirloin", "quantity": 6, "unit": "oz"},
            {"name": "broccoli", "quantity": 1, "unit": "cup"},
            {"name": "carrot", "quantity": 1, "unit": "unit"},
            {"name": "jasmine rice", "quantity": 1, "unit": "cup"},
            {"name": "soy sauce", "quantity": 2, "unit": "tbsp"},
        ],
    },
    {
        "name": "Chickpea Coconut Curry",
        "description": "Chickpeas simmered in coconut curry sauce over rice.",
        "meal_type": models.MealType.DINNER,
        "calories": 610,
        "protein_g": 18,
        "carbs_g": 78,
        "fat_g": 24,
        "dietary_tags": ["vegetarian", "vegan", "gluten_free"],
        "allergens": [],
        "ingredients": [
            {"name": "chickpeas", "quantity": 1.5, "unit": "cup"},
            {"name": "coconut milk", "quantity": 1, "unit": "cup"},
            {"name": "curry paste", "quantity": 2, "unit": "tbsp"},
            {"name": "jasmine rice", "quantity": 1, "unit": "cup"},
        ],
    },
    {
        "name": "Zucchini Noodle Bolognese",
        "description": "Spiralized zucchini with a beef and tomato ragu.",
        "meal_type": models.MealType.DINNER,
        "calories": 480,
        "protein_g": 32,
        "carbs_g": 20,
        "fat_g": 30,
        "dietary_tags": ["gluten_free", "keto", "paleo", "high_protein", "low_carb"],
        "allergens": ["dairy"],
        "ingredients": [
            {"name": "zucchini", "quantity": 2, "unit": "unit"},
            {"name": "ground beef", "quantity": 6, "unit": "oz"},
            {"name": "tomato sauce", "quantity": 1, "unit": "cup"},
            {"name": "parmesan cheese", "quantity": 2, "unit": "tbsp"},
        ],
    },
    {
        "name": "Margherita Pizza",
        "description": "Thin crust pizza with tomato, mozzarella, and basil.",
        "meal_type": models.MealType.DINNER,
        "calories": 700,
        "protein_g": 26,
        "carbs_g": 82,
        "fat_g": 28,
        "dietary_tags": ["vegetarian"],
        "allergens": ["gluten", "dairy"],
        "ingredients": [
            {"name": "pizza dough", "quantity": 1, "unit": "unit"},
            {"name": "mozzarella cheese", "quantity": 1, "unit": "cup"},
            {"name": "tomato sauce", "quantity": 0.5, "unit": "cup"},
            {"name": "basil", "quantity": 6, "unit": "leaf"},
        ],
    },
    {
        "name": "Lentil Soup",
        "description": "Hearty lentil soup with carrots, celery, and cumin.",
        "meal_type": models.MealType.DINNER,
        "calories": 420,
        "protein_g": 22,
        "carbs_g": 60,
        "fat_g": 8,
        "dietary_tags": ["vegetarian", "vegan", "gluten_free"],
        "allergens": [],
        "ingredients": [
            {"name": "lentils", "quantity": 1.5, "unit": "cup"},
            {"name": "carrot", "quantity": 1, "unit": "unit"},
            {"name": "celery", "quantity": 1, "unit": "stalk"},
            {"name": "vegetable broth", "quantity": 3, "unit": "cup"},
        ],
    },
    {
        "name": "Grilled Steak with Roasted Vegetables",
        "description": "Grilled sirloin steak with roasted broccoli and peppers.",
        "meal_type": models.MealType.DINNER,
        "calories": 620,
        "protein_g": 42,
        "carbs_g": 18,
        "fat_g": 38,
        "dietary_tags": ["keto", "paleo", "gluten_free", "high_protein", "low_carb"],
        "allergens": [],
        "ingredients": [
            {"name": "sirloin steak", "quantity": 8, "unit": "oz"},
            {"name": "broccoli", "quantity": 1, "unit": "cup"},
            {"name": "bell pepper", "quantity": 1, "unit": "unit"},
            {"name": "olive oil", "quantity": 1, "unit": "tbsp"},
        ],
    },
    {
        "name": "Herb Roasted Chicken with Green Beans",
        "description": "Herb-roasted chicken thighs with garlicky green beans.",
        "meal_type": models.MealType.DINNER,
        "calories": 560,
        "protein_g": 44,
        "carbs_g": 12,
        "fat_g": 32,
        "dietary_tags": ["gluten_free", "paleo", "keto", "high_protein", "low_carb"],
        "allergens": [],
        "ingredients": [
            {"name": "chicken thighs", "quantity": 8, "unit": "oz"},
            {"name": "green beans", "quantity": 1.5, "unit": "cup"},
            {"name": "olive oil", "quantity": 1, "unit": "tbsp"},
            {"name": "garlic", "quantity": 2, "unit": "clove"},
        ],
    },
    {
        "name": "Pan-Seared Cod with Lemon Butter",
        "description": "Flaky cod fillet in a lemon butter sauce with asparagus.",
        "meal_type": models.MealType.DINNER,
        "calories": 420,
        "protein_g": 36,
        "carbs_g": 6,
        "fat_g": 24,
        "dietary_tags": ["pescatarian", "gluten_free", "keto", "paleo", "high_protein", "low_carb"],
        "allergens": ["fish", "dairy"],
        "ingredients": [
            {"name": "cod fillet", "quantity": 8, "unit": "oz"},
            {"name": "butter", "quantity": 2, "unit": "tbsp"},
            {"name": "lemon", "quantity": 1, "unit": "unit"},
            {"name": "asparagus", "quantity": 1, "unit": "bunch"},
        ],
    },
    {
        "name": "Garlic Butter Shrimp with Cauliflower Rice",
        "description": "Garlic butter shrimp served over cauliflower rice.",
        "meal_type": models.MealType.DINNER,
        "calories": 440,
        "protein_g": 32,
        "carbs_g": 14,
        "fat_g": 28,
        "dietary_tags": ["pescatarian", "gluten_free", "keto", "paleo", "high_protein", "low_carb"],
        "allergens": ["shellfish", "dairy"],
        "ingredients": [
            {"name": "shrimp", "quantity": 8, "unit": "oz"},
            {"name": "cauliflower rice", "quantity": 1.5, "unit": "cup"},
            {"name": "butter", "quantity": 2, "unit": "tbsp"},
            {"name": "garlic", "quantity": 3, "unit": "clove"},
        ],
    },
    {
        "name": "Baked Tilapia with Roasted Broccoli",
        "description": "Lemon-baked tilapia with roasted broccoli.",
        "meal_type": models.MealType.DINNER,
        "calories": 400,
        "protein_g": 34,
        "carbs_g": 10,
        "fat_g": 22,
        "dietary_tags": ["pescatarian", "gluten_free", "keto", "high_protein", "low_carb"],
        "allergens": ["fish"],
        "ingredients": [
            {"name": "tilapia fillet", "quantity": 8, "unit": "oz"},
            {"name": "broccoli", "quantity": 1.5, "unit": "cup"},
            {"name": "olive oil", "quantity": 1, "unit": "tbsp"},
            {"name": "lemon", "quantity": 0.5, "unit": "unit"},
        ],
    },
    {
        "name": "Seared Tuna Steak with Asian Slaw",
        "description": "Seared tuna steak over a crunchy sesame-tamari slaw.",
        "meal_type": models.MealType.DINNER,
        "calories": 440,
        "protein_g": 38,
        "carbs_g": 14,
        "fat_g": 22,
        "dietary_tags": ["pescatarian", "gluten_free", "high_protein", "low_carb"],
        "allergens": ["fish", "soy", "sesame"],
        "ingredients": [
            {"name": "tuna steak", "quantity": 7, "unit": "oz"},
            {"name": "cabbage slaw", "quantity": 1.5, "unit": "cup"},
            {"name": "sesame oil", "quantity": 1, "unit": "tbsp"},
            {"name": "tamari", "quantity": 1, "unit": "tbsp"},
        ],
    },
    {
        "name": "Vegan Stuffed Peppers",
        "description": "Bell peppers stuffed with quinoa, black beans, and salsa.",
        "meal_type": models.MealType.DINNER,
        "calories": 460,
        "protein_g": 18,
        "carbs_g": 62,
        "fat_g": 16,
        "dietary_tags": ["vegan", "vegetarian", "gluten_free", "high_protein"],
        "allergens": [],
        "ingredients": [
            {"name": "bell pepper", "quantity": 3, "unit": "unit"},
            {"name": "quinoa", "quantity": 1, "unit": "cup"},
            {"name": "black beans", "quantity": 1, "unit": "cup"},
            {"name": "salsa", "quantity": 0.5, "unit": "cup"},
        ],
    },
    {
        "name": "Eggplant Parmesan",
        "description": "Breaded eggplant baked with tomato sauce and mozzarella.",
        "meal_type": models.MealType.DINNER,
        "calories": 560,
        "protein_g": 24,
        "carbs_g": 48,
        "fat_g": 30,
        "dietary_tags": ["vegetarian", "gluten_free"],
        "allergens": ["dairy"],
        "ingredients": [
            {"name": "eggplant", "quantity": 1, "unit": "unit"},
            {"name": "mozzarella cheese", "quantity": 1, "unit": "cup"},
            {"name": "tomato sauce", "quantity": 1, "unit": "cup"},
            {"name": "gluten-free breadcrumbs", "quantity": 0.5, "unit": "cup"},
            {"name": "parmesan cheese", "quantity": 2, "unit": "tbsp"},
        ],
    },
    {
        "name": "Vegan Mushroom Risotto",
        "description": "Creamy arborio rice risotto with sauteed mushrooms.",
        "meal_type": models.MealType.DINNER,
        "calories": 520,
        "protein_g": 12,
        "carbs_g": 78,
        "fat_g": 16,
        "dietary_tags": ["vegan", "vegetarian", "gluten_free"],
        "allergens": [],
        "ingredients": [
            {"name": "arborio rice", "quantity": 1, "unit": "cup"},
            {"name": "mushroom", "quantity": 1.5, "unit": "cup"},
            {"name": "vegetable broth", "quantity": 3, "unit": "cup"},
            {"name": "nutritional yeast", "quantity": 2, "unit": "tbsp"},
        ],
    },
    {
        "name": "Stuffed Portobello Mushrooms",
        "description": "Portobello caps stuffed with quinoa and spinach.",
        "meal_type": models.MealType.DINNER,
        "calories": 380,
        "protein_g": 14,
        "carbs_g": 32,
        "fat_g": 22,
        "dietary_tags": ["vegan", "vegetarian", "gluten_free"],
        "allergens": [],
        "ingredients": [
            {"name": "portobello mushroom", "quantity": 4, "unit": "unit"},
            {"name": "quinoa", "quantity": 0.5, "unit": "cup"},
            {"name": "spinach", "quantity": 1, "unit": "cup"},
            {"name": "olive oil", "quantity": 1, "unit": "tbsp"},
        ],
    },
    {
        "name": "Thai Green Curry with Tofu",
        "description": "Tofu and vegetables simmered in Thai green curry sauce.",
        "meal_type": models.MealType.DINNER,
        "calories": 540,
        "protein_g": 20,
        "carbs_g": 56,
        "fat_g": 26,
        "dietary_tags": ["vegan", "vegetarian", "gluten_free"],
        "allergens": ["soy"],
        "ingredients": [
            {"name": "tofu", "quantity": 8, "unit": "oz"},
            {"name": "coconut milk", "quantity": 1, "unit": "cup"},
            {"name": "curry paste", "quantity": 2, "unit": "tbsp"},
            {"name": "broccoli", "quantity": 1, "unit": "cup"},
            {"name": "jasmine rice", "quantity": 1, "unit": "cup"},
        ],
    },
    {
        "name": "Turkey Meatballs with Zucchini Noodles",
        "description": "Baked turkey meatballs over zucchini noodles in marinara.",
        "meal_type": models.MealType.DINNER,
        "calories": 460,
        "protein_g": 36,
        "carbs_g": 16,
        "fat_g": 26,
        "dietary_tags": ["gluten_free", "paleo", "high_protein", "low_carb"],
        "allergens": [],
        "ingredients": [
            {"name": "ground turkey", "quantity": 8, "unit": "oz"},
            {"name": "zucchini", "quantity": 2, "unit": "unit"},
            {"name": "tomato sauce", "quantity": 1, "unit": "cup"},
            {"name": "almond flour", "quantity": 0.25, "unit": "cup"},
        ],
    },
    {
        "name": "Pork Tenderloin with Roasted Brussels Sprouts",
        "description": "Roasted pork tenderloin with caramelized brussels sprouts.",
        "meal_type": models.MealType.DINNER,
        "calories": 500,
        "protein_g": 40,
        "carbs_g": 16,
        "fat_g": 28,
        "dietary_tags": ["paleo", "keto", "gluten_free", "high_protein", "low_carb"],
        "allergens": [],
        "ingredients": [
            {"name": "pork tenderloin", "quantity": 8, "unit": "oz"},
            {"name": "brussels sprouts", "quantity": 1.5, "unit": "cup"},
            {"name": "olive oil", "quantity": 1, "unit": "tbsp"},
        ],
    },
    {
        "name": "Chicken Fajita Bowl",
        "description": "Fajita-spiced chicken and peppers over cauliflower rice.",
        "meal_type": models.MealType.DINNER,
        "calories": 520,
        "protein_g": 38,
        "carbs_g": 18,
        "fat_g": 30,
        "dietary_tags": ["gluten_free", "keto", "paleo", "high_protein", "low_carb"],
        "allergens": [],
        "ingredients": [
            {"name": "chicken breast", "quantity": 6, "unit": "oz"},
            {"name": "bell pepper", "quantity": 1, "unit": "unit"},
            {"name": "onion", "quantity": 0.5, "unit": "unit"},
            {"name": "cauliflower rice", "quantity": 1, "unit": "cup"},
            {"name": "olive oil", "quantity": 1, "unit": "tbsp"},
        ],
    },
    {
        "name": "Vegan Chili",
        "description": "Hearty three-bean chili with tomato and peppers.",
        "meal_type": models.MealType.DINNER,
        "calories": 480,
        "protein_g": 20,
        "carbs_g": 72,
        "fat_g": 12,
        "dietary_tags": ["vegan", "vegetarian", "gluten_free", "high_protein"],
        "allergens": [],
        "ingredients": [
            {"name": "black beans", "quantity": 1.5, "unit": "cup"},
            {"name": "kidney beans", "quantity": 1, "unit": "cup"},
            {"name": "tomato sauce", "quantity": 1, "unit": "cup"},
            {"name": "bell pepper", "quantity": 1, "unit": "unit"},
            {"name": "onion", "quantity": 0.5, "unit": "unit"},
        ],
    },
    {
        "name": "Butternut Squash Soup",
        "description": "Creamy roasted butternut squash soup with coconut milk.",
        "meal_type": models.MealType.DINNER,
        "calories": 340,
        "protein_g": 8,
        "carbs_g": 54,
        "fat_g": 10,
        "dietary_tags": ["vegetarian", "vegan", "gluten_free"],
        "allergens": [],
        "ingredients": [
            {"name": "butternut squash", "quantity": 2, "unit": "cup"},
            {"name": "vegetable broth", "quantity": 2, "unit": "cup"},
            {"name": "coconut milk", "quantity": 0.5, "unit": "cup"},
            {"name": "onion", "quantity": 0.5, "unit": "unit"},
        ],
    },
    {
        "name": "Baked Chicken Thighs with Sweet Potato",
        "description": "Oven-baked chicken thighs with roasted sweet potato.",
        "meal_type": models.MealType.DINNER,
        "calories": 560,
        "protein_g": 40,
        "carbs_g": 34,
        "fat_g": 26,
        "dietary_tags": ["paleo", "gluten_free", "high_protein"],
        "allergens": [],
        "ingredients": [
            {"name": "chicken thighs", "quantity": 8, "unit": "oz"},
            {"name": "sweet potato", "quantity": 1, "unit": "unit"},
            {"name": "olive oil", "quantity": 1, "unit": "tbsp"},
        ],
    },
    {
        "name": "Beef and Broccoli",
        "description": "Sliced beef and broccoli in a savory tamari sauce.",
        "meal_type": models.MealType.DINNER,
        "calories": 480,
        "protein_g": 36,
        "carbs_g": 22,
        "fat_g": 26,
        "dietary_tags": ["gluten_free", "high_protein", "low_carb"],
        "allergens": ["soy"],
        "ingredients": [
            {"name": "beef sirloin", "quantity": 7, "unit": "oz"},
            {"name": "broccoli", "quantity": 1.5, "unit": "cup"},
            {"name": "tamari", "quantity": 2, "unit": "tbsp"},
            {"name": "ginger", "quantity": 1, "unit": "tbsp"},
        ],
    },
    {
        "name": "Vegetarian Fajita Bowl",
        "description": "Sauteed peppers, onion, and black beans over rice.",
        "meal_type": models.MealType.DINNER,
        "calories": 460,
        "protein_g": 14,
        "carbs_g": 68,
        "fat_g": 16,
        "dietary_tags": ["vegetarian", "vegan", "gluten_free"],
        "allergens": [],
        "ingredients": [
            {"name": "bell pepper", "quantity": 1.5, "unit": "unit"},
            {"name": "onion", "quantity": 0.5, "unit": "unit"},
            {"name": "black beans", "quantity": 1, "unit": "cup"},
            {"name": "jasmine rice", "quantity": 1, "unit": "cup"},
            {"name": "salsa", "quantity": 0.25, "unit": "cup"},
        ],
    },
    {
        "name": "Miso Glazed Salmon",
        "description": "Salmon fillet glazed with sweet miso, served with rice.",
        "meal_type": models.MealType.DINNER,
        "calories": 520,
        "protein_g": 36,
        "carbs_g": 22,
        "fat_g": 30,
        "dietary_tags": ["pescatarian", "gluten_free", "high_protein"],
        "allergens": ["fish", "soy"],
        "ingredients": [
            {"name": "salmon fillet", "quantity": 7, "unit": "oz"},
            {"name": "miso paste", "quantity": 2, "unit": "tbsp"},
            {"name": "jasmine rice", "quantity": 1, "unit": "cup"},
            {"name": "broccoli", "quantity": 1, "unit": "cup"},
        ],
    },
]

SAMPLE_MEALS = BREAKFAST_MEALS + LUNCH_MEALS + DINNER_MEALS


def seed() -> None:
    Base.metadata.create_all(bind=engine)
    db = SessionLocal()
    try:
        if db.query(models.Meal).first() is not None:
            print("Meals already exist, skipping seed.")
            return

        for data in SAMPLE_MEALS:
            data = dict(data)
            ingredients = data.pop("ingredients")
            meal = models.Meal(**data)
            for item in ingredients:
                ingredient = db.query(models.Ingredient).filter(models.Ingredient.name == item["name"]).first()
                if ingredient is None:
                    ingredient = models.Ingredient(name=item["name"])
                    db.add(ingredient)
                    db.flush()
                meal.ingredient_links.append(
                    models.MealIngredient(ingredient=ingredient, quantity=item["quantity"], unit=item["unit"])
                )
            db.add(meal)

        db.commit()
        print(f"Seeded {len(SAMPLE_MEALS)} meals.")
    finally:
        db.close()


if __name__ == "__main__":
    seed()
